// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqfHrLKYk9qpZzZNI6U7wynjmanUMU3w8',
    appId: '1:375685983796:web:0bc2dece0207d530f72461',
    messagingSenderId: '375685983796',
    projectId: 'products-challenge-ca64d',
    authDomain: 'products-challenge-ca64d.firebaseapp.com',
    storageBucket: 'products-challenge-ca64d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70kkk3JpIFldM-QRoRRGN8Jp2g1hIU1c',
    appId: '1:375685983796:android:810081d6b8c1ec13f72461',
    messagingSenderId: '375685983796',
    projectId: 'products-challenge-ca64d',
    storageBucket: 'products-challenge-ca64d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWEWT_TqdB-ix01lM4fEY0UrOYQ0B5UPw',
    appId: '1:375685983796:ios:6cda98f346d97e7ff72461',
    messagingSenderId: '375685983796',
    projectId: 'products-challenge-ca64d',
    storageBucket: 'products-challenge-ca64d.appspot.com',
    iosClientId:
        '375685983796-qqbm7ud2rrsk9jpbt5bov6v3qmoaf7eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.productsChallenge',
  );
}
